language: python
sudo: required
python:
  - "3.5"
  - "3.6"
  - "3.7"
env: TEST_SUITE=test-main
matrix:
  include:
  - python: "2.7"
    env: TEST_SUITE=test-py2-legacy-support
  - python: "3.6"
    env: TEST_SUITE=test-static-analysis
    addons:
      postgresql: "9.3"
install:
  - sudo rm -vf /etc/apt/sources.list.d/*
  - sudo apt-get update
  - tools/provision --force
  - source zulip-api-py*-venv/bin/activate
script:
  - tools/$TEST_SUITE
after_success:
  - pip install codecov
  - codecov
